# Generated by Django 2.0.3 on 2018-03-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_pic',
            field=models.ImageField(default='media/userpicks/maxresdefault.jpg', upload_to='media/event_pics/'),
        ),
    ]
