# Generated by Django 2.0.3 on 2018-03-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0002_event_event_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_pic',
            field=models.ImageField(default='media/userpicks/maxresdefault.jpg', upload_to='event_pics/'),
        ),
    ]
