# Generated by Django 2.0.3 on 2018-03-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0003_auto_20180325_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
