# Generated by Django 2.0.3 on 2018-03-26 14:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hobby', '0004_auto_20180325_2119'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_profile',
            new_name='Profile',
        ),
    ]
