# Generated by Django 2.0.3 on 2018-03-30 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0006_like_is_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='is_liked',
        ),
    ]
