# Generated by Django 2.0.3 on 2018-03-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0007_remove_like_is_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_pic',
            field=models.ImageField(default='static/design-11.jpg', upload_to=''),
        ),
    ]
