# Generated by Django 2.0.3 on 2018-03-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0008_auto_20180330_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_pic',
            field=models.ImageField(default='design-11.jpg', upload_to=''),
        ),
    ]
