# Generated by Django 2.0.3 on 2018-03-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0009_auto_20180330_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_pic',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
