# Generated by Django 2.0 on 2018-03-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0009_auto_20180319_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='associated_with',
            field=models.ManyToManyField(related_name='events', to='hobby.Board'),
        ),
    ]
