# Generated by Django 2.0 on 2018-03-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0011_auto_20180320_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='is_organizer',
            field=models.BooleanField(default=False),
        ),
    ]
