# Generated by Django 2.0 on 2018-03-20 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0012_user_profile_is_organizer'),
    ]

    operations = [

    ]
