# Generated by Django 2.0.3 on 2018-04-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0013_auto_20180403_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='board_pic',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
