# Generated by Django 2.0 on 2018-03-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0014_auto_20180320_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='associated_with',
        ),
    ]
