# Generated by Django 2.0.3 on 2018-04-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0014_board_board_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to=''),
        ),
    ]
