# Generated by Django 2.0 on 2018-03-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0015_remove_event_associated_with'),
    ]

    operations = [

    ]
