# Generated by Django 2.0.3 on 2018-09-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0016_board_back_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
