# Generated by Django 2.0 on 2018-03-20 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0016_event_associated_with'),
    ]

    operations = [

    ]
