# Generated by Django 2.0.3 on 2018-09-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0017_auto_20180925_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
