# Generated by Django 2.0 on 2018-03-20 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0017_remove_event_associated_with'),
    ]

    operations = [
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hobby.Board')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hobby.Event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='associated_with',
            field=models.ManyToManyField(through='hobby.Associate', to='hobby.Board'),
        ),
    ]
