# Generated by Django 2.0.3 on 2018-09-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0018_auto_20180925_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('model_name', models.CharField(max_length=30)),
            ],
        ),
    ]
