# Generated by Django 2.0 on 2018-03-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0018_auto_20180320_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='associated_with',
            field=models.ManyToManyField(related_name='events', through='hobby.Associate', to='hobby.Board'),
        ),
    ]
