# Generated by Django 2.0.3 on 2018-09-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0019_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='picture',
            field=models.FileField(upload_to=''),
        ),
    ]
