# Generated by Django 2.0 on 2018-03-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0020_auto_20180320_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='events',
            new_name='boards',
        ),
    ]
