# Generated by Django 2.0.3 on 2018-09-28 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0020_auto_20180928_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='picture',
            new_name='file',
        ),
    ]
