# Generated by Django 2.0.3 on 2018-09-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0022_auto_20180930_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='board_pic',
            new_name='pic',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_pic',
        ),
        migrations.AddField(
            model_name='event',
            name='pic',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
