# Generated by Django 2.0.3 on 2018-09-30 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0023_auto_20180930_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='back_img',
        ),
    ]
