# Generated by Django 2.0.3 on 2018-10-04 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0026_auto_20181001_1536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
