# Generated by Django 2.0.3 on 2018-10-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileSynchronizer',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('model_name', models.CharField(max_length=30)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
